---
- name: Ensure haproxy is installed
  apt: name=haproxy state=present

- name: Ensure haproxy is enabled
  lineinfile:
    dest: /etc/default/haproxy
    regexp: "^ENABLED.+$" # Regex search
    line: "ENABLED=1" # Value in line
    state: present # Sets it to present

- name: Copy haproxy config file
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    mode: 0644
  notify: restart haproxy

- name: Ensure haproxy us started and enabled on boot
  service: name=haproxy state=started enabled=yes
